### ISSUE TITLE
Вопрос :-)

### ISSUE THREAD

**Issue by AlehAkbashev** [yolkbaron/lpr-python#2]
Не нашел иного способа связаться с вами. 
Разбираюсь с практикой по питону и нашел ваше решение задачи с моделированием реального газа. 
Может, пожалуйста, пояснить вот этот кусочек кода. Что это формулы значат и как вы их получили?
u = -((x1-x2)*(vx1-vx2)/d + (y1-y2)*(vy1-vy2)/d) #change in the speed of the first atom
vx[atom] += u*(x1-x2)/d
vx[atom2] -= u*(x1-x2)/d
vy[atom] += u*(y1-y2)/d
vy[atom2] -= u*(y1-y1)/d

И ошибка в последней строчке: vy[atom2] -= u*(y1-**y2**)/d

**Comment by yolkbaron** [comment]
![image](https://user-images.githubusercontent.com/71354158/100388462-b999cc00-303b-11eb-8197-81b38f39a090.png)
Вроде здесь почти всё написал, u - модуль вектора изменения скорости atmo, у atom2 это будет -u.
Последние 4 строчки - проекции u на Ox и Oy. Надеюсь, помог разобраться.

Спасибо, что обратили внимание на ошибку, исправил.

**Comment by AlehAkbashev** [comment]
Я понял почти все, кроме U в первой строчке. U равна разнице скоростей V1 и
V2? Величина переменная, так как меняется скорость и расстояние между
молекулами?
И еще момент, который, как мне кажется, ошибочен: Проекция V2 на U даст нам
-V2, который равен сумме векторов V2x и V2y. Косинусы и синусы пока не
нужны. А вот когда мы будем расписывать V2x и V2y, то тогда появятся синусы
и косинусы, которые мы будем умножать на V2, то есть по формуле они синусы
и косинусы не нужны, если мы ищем V2, a V2x и V2y нам уже известны. Но сам
по себе V2 можно найти просто поделив V2x на cos(A) и так же найти V1. Я
могу ошибаться. Если вы проверите мою логику и покритикуете, то будет
здорово!)
Вам уже спасибо хотя бы за обратную связь!


чт, 26 нояб. 2020 г. в 23:06, Daniil Sakharov <notifications@github.com>:

**Comment by yolkbaron** [comment]
u равна разнице скорости atmo до столкновения и скорости atmo после столкновения. На картинке я вывел формулу. u считается для конкретного столкновения и является служебной величиной, которую я нигде не храню после расчёта данного столкновения.
Про проекции: ось u наклонена относительно Ox и alpha - угол этого наклона u. Проекция V2 на u это не -V2 так как вектор u направлен от одного центра шара к другому, а V2 - произвольным образом. Когда я пишу проекции я раскладываю V2 на 2 компоненты V2x и V2y (на рисунке они подразумеваются скалярами, поэтому сразу есть косинус и синус) и потом эти компоненты проецирую на u (здесь мы уже знаем их направления и поэтому можем посчитать проекции).

**Comment by yolkbaron** [comment]
![image](https://user-images.githubusercontent.com/71354158/100391482-9cb5c680-3044-11eb-8e63-209807dfc9f3.png)
Здесь подробнее расписал про проекции, знаки определяются исходя из направления осей Ox и Oy.

**Comment by AlehAkbashev** [comment]
Да, очень здорово все выглядит. Спасибо за ответ.
Сейчас проанализирую.

пт, 27 нояб. 2020 г. в 00:08, Daniil Sakharov <notifications@github.com>:

**Comment by AlehAkbashev** [comment]
*u равна разнице скорости atmo до столкновения и скорости atmo после
столкновения.   *
Скорость атома №1 после столкновения равна скорости атома №2 до
столкновения? Я уже немного в физику процесса углубился.

пт, 27 нояб. 2020 г. в 00:13, Aleh Akbashev <akbashevaleh@gmail.com>:

**Comment by yolkbaron** [comment]
Почти. Проекция скорости атома 1 на u до удара равно проекции скорости атома 2 после.
